### ISSUE TITLE
Change observation error model?

### ISSUE THREAD

**Issue by sdwfrost** [dsheldon/covid#3]
Hi @dsheldon! This looks very nice - I managed to install/run OOTB, but I was a bit concerned about the use of cumulative data as the observation model - there are lots of issues with it, as described by Aaron King [here](https://royalsocietypublishing.org/doi/full/10.1098/rspb.2015.0347). Could you try switching out to a negative binomial on new cases/deaths per day?

**Comment by dsheldon** [comment]
Hi @sdwfrost thanks for the feedback! We'll definitely take a look at the King paper.

Short answer: our first instinct/preference when developing the model was to have observations on new cases/deaths, but we ran into into a number of technical issues. Some of those are resolved by now, so it could be worth another try. 

For reference, here are the possible remaining issues:

1. Possible issues with negative binomial support in numpyro. See https://github.com/pyro-ppl/numpyro/issues/563. Forcing double precision as described in that issue may work, but since I had already struggled significantly with stability issues when trying different observation models (some of them due to rough edges of numpyro) I made the pragmatic choice to use a normal distribution. This is a separate issue from observing cumulative vs. incident deaths.

2. There is some partial work on observing new cases/deaths in the branch `daily` (the branch is a bit stale, but it would by easy to reproduce this in the current `master`). This runs, but some quick qualitative results suggested it needed more tuning/investigation to be completely satisfactory. Qualitatively, the noise model seemed to allow it to "ignore" some phases of the pandemic. It would give satisfactory fits to incident cases but show some obvious "errors" relative to cumulative cases. This was a very quick investigation, though. I'd like to see more work on this.

**Comment by dsheldon** [comment]
We now have a model with negative binomial observations on daily cases/deaths. See models/SEIRD_incident.py. 

It may be important to use `numpyro.enable_x64()` to enable 64-bit precision with this model. (After a bunch of fussy changes to get it working, I haven't tested without to know if it's strictly necessary.)
