### ISSUE TITLE
latest numpyro from git conflicts with specified jax version

### ISSUE THREAD

**Issue by wilkie** [dsheldon/covid#9]
Since the jax/jaxlib package has some horrible regression, numpyro pinned jax to `2.8.0` in its git repo, which conflicts with the version in your `setup.py`. You are always installing the latest numpyro via specifying the git repository instead of a version string in your `setup.py`

It is likely good to remove the jax/jaxlib versions specified in your `setup.py` (and rely on `numpyro` specifying them), or specify them with `>=` or (perhaps best?) pin the version of `numpyro` to one that can use those versions of `jax`. I believe that version should be 0.4.1, but that requires also setting jaxlib to `0.1.56`. (Easier to just remove jax/jaxlib from your `setup.py` perhaps.)

It also possible to attach the exact revision you intended by using the line:

`'numpyro @ git+https://github.com/pyro-ppl/numpyro.git@d727d59d282828a1f9c3f233cbcdc80de5a3dc56#egg=numpyro'`

Although I'm guessing at what revision of numpyro you intended to use. This one is the latest one that will still use the versions of jax and jaxlib you describe in your `setup.py`. In the future, specifying an exact revision will prevent upstream changes from magically breaking your scripts.

Cheers.

**Comment by dsheldon** [comment]
Thanks for this pointer and recommendations. Way back at the beginning of the project we were relying on not-yet-released bug-fixes to numpyro, and I didn't really know how to write a setup.py ;). 

Things are pretty stable now, so I've simplified `setup.py` with commit 31355a1c0cebc4e394ffa8c9ab1ad018da6cacaf. I went with 

* `numpyro >= 0.4.1`
* `jax >= 0.2.3`

Since we use jax directly, I thought it reasonable to add the dependency directly, though I can't imagine a world where numpyro does not automatically pull in jax.
